alias c='clear'
alias fs='foreman start'
alias vu='vagrant up'
alias vh='vagrant halt'
alias vs='ssh vagrant'
alias vsp='ssh personal'
alias vr='vagrant resume'
alias vsusp='vagrant suspend'
alias tma='tmux a -t '
alias tmn='tmux new -s '
alias tmk='tmux kill-session -t '
alias tmls='tmux ls'
alias restartnet='sudo /etc/init.d/networking restart'

# Empower my idiosyncratic typos
alias gti='git'
